### ISSUE TITLE
SSH Key Access

### ISSUE THREAD

**Issue by DarkArc** [flathub/org.gnome.World.PikaBackup#156]
Perhaps it's obvious, but how does Pika get the SSH key access within flatpak? Does the SSH key need to be installed to a specific place? Does it have to have a specific name?

**Comment by tjaartvdwalt** [comment]
Maybe you have resolved this, but I had the same problem today.
You can customize the SSH command by using the `BORG_RSH` environment variable.

The following code worked for me:
```bash
BORG_RSH="ssh -i /path/to/my/private_key" pika-backup
```

**Comment by DarkArc** [comment]
I ended up using Kopia instead, but good note! Hope it helps someone else.

**Comment by sophie-h** [comment]
The Pika Backup issue tracker is here https://gitlab.gnome.org/World/pika-backup

**Comment by DarkArc** [comment]
@sophie-h I opened this here because I assumed the behavior is different outside of a flatpak.
