### ISSUE TITLE
Error regarding to gnome-keyring

### ISSUE THREAD

**Issue by eylenburg** [flathub/org.gnome.World.PikaBackup#167]
I tried setting up an encrypted backup, but it would fail and say something about gnome-keyring. (Don't have the exact message now as I'm on another device.) Maybe something needs to be added to the dependencies in the manifest?

I use KDE Plasma btw if that matters

**Comment by sophie-h** [comment]
You need to have something that provides the secret portal. That usually requires having a working secret service implementation running on your host. The error message should give you further details.

**Comment by eylenburg** [comment]
On Plasma that would probably be KWallet. I haven't had this issue with any other app.

I just had a look at the manifest of [DejaDup ](https://github.com/flathub/org.gnome.DejaDup/blob/master/org.gnome.DejaDup.yaml)(where I didn't encounter this problem with an encrypted backup) and it contains `talk-name=org.freedesktop.secrets` - is that perhaps why it works?

**Comment by sophie-h** [comment]
As you can see with the comment, DejaDup uses a legacy method

> # drop when xdg-desktop-portal 1.5.0 (2019) is everywhere

Please contact your distro on how to get the [secrets portal](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.Secret.html) working on your PC.
