### ISSUE TITLE
Add missing --talk-name=org.gtk.vfs

### ISSUE THREAD

**Issue by hadess** [flathub/org.gnome.World.PikaBackup#7]
`--talk-name=org.gtk.vfs.*` isn't enough to talk to gvfsd, you'll also need `--talk-name=org.gtk.vfs`, as well as access to the directory with the socket to talk to gvfs (see https://github.com/flathub/flathub/issues/2180)

**Comment by sophie-h** [comment]
Thanks! Does this needs to be changed before the flatpaks runtime changes to 40?

**Comment by sophie-h** [comment]
Fixed. Thanks again for the help!
